-- V4__fix_missing_base_entity_columns.sql
-- Align CMS tables with common.persistence.BaseEntity for existing PostgreSQL databases.

ALTER TABLE media ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE media ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE media ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE media ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE media
SET is_active = COALESCE(is_active, TRUE),
    is_deleted = COALESCE(is_deleted, FALSE),
    created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
    updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP);

ALTER TABLE media ALTER COLUMN is_active SET DEFAULT TRUE;
ALTER TABLE media ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE media ALTER COLUMN is_deleted SET DEFAULT FALSE;
ALTER TABLE media ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE media ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE media ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE media ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE media ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE pages ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE pages
SET is_active = COALESCE(is_active, TRUE),
    is_deleted = COALESCE(is_deleted, FALSE),
    created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
    updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP);

ALTER TABLE pages ALTER COLUMN is_active SET DEFAULT TRUE;
ALTER TABLE pages ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE pages ALTER COLUMN is_deleted SET DEFAULT FALSE;
ALTER TABLE pages ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE pages ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE pages ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE pages ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE pages ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE page_sections ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE page_sections ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE page_sections ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE page_sections ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE page_sections
SET is_active = COALESCE(is_active, TRUE),
    is_deleted = COALESCE(is_deleted, FALSE),
    created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
    updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP);

ALTER TABLE page_sections ALTER COLUMN is_active SET DEFAULT TRUE;
ALTER TABLE page_sections ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE page_sections ALTER COLUMN is_deleted SET DEFAULT FALSE;
ALTER TABLE page_sections ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE page_sections ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE page_sections ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE page_sections ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE page_sections ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE home_sections ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE home_sections ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE home_sections ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE home_sections ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE home_sections
SET is_active = COALESCE(is_active, TRUE),
    is_deleted = COALESCE(is_deleted, FALSE),
    created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
    updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP);

ALTER TABLE home_sections ALTER COLUMN is_active SET DEFAULT TRUE;
ALTER TABLE home_sections ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE home_sections ALTER COLUMN is_deleted SET DEFAULT FALSE;
ALTER TABLE home_sections ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE home_sections ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE home_sections ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE home_sections ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE home_sections ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE banners ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE banners ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE banners ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE banners ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE banners
SET is_active = COALESCE(is_active, TRUE),
    is_deleted = COALESCE(is_deleted, FALSE),
    created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
    updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP);

ALTER TABLE banners ALTER COLUMN is_active SET DEFAULT TRUE;
ALTER TABLE banners ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE banners ALTER COLUMN is_deleted SET DEFAULT FALSE;
ALTER TABLE banners ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE banners ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE banners ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE banners ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE banners ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE testimonials
SET is_active = COALESCE(is_active, TRUE),
    is_deleted = COALESCE(is_deleted, FALSE),
    created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
    updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP);

ALTER TABLE testimonials ALTER COLUMN is_active SET DEFAULT TRUE;
ALTER TABLE testimonials ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE testimonials ALTER COLUMN is_deleted SET DEFAULT FALSE;
ALTER TABLE testimonials ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE testimonials ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE testimonials ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE testimonials ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE testimonials ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE lookbooks ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0;
ALTER TABLE lookbooks ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE lookbooks ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE lookbooks ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE lookbooks ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE lookbooks
SET display_order = COALESCE(display_order, 0),
    is_active = COALESCE(is_active, TRUE),
    is_deleted = COALESCE(is_deleted, FALSE),
    created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
    updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP);

ALTER TABLE lookbooks ALTER COLUMN display_order SET DEFAULT 0;
ALTER TABLE lookbooks ALTER COLUMN is_active SET DEFAULT TRUE;
ALTER TABLE lookbooks ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE lookbooks ALTER COLUMN is_deleted SET DEFAULT FALSE;
ALTER TABLE lookbooks ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE lookbooks ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE lookbooks ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE lookbooks ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE lookbooks ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE faq_categories ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE faq_categories ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE faq_categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE faq_categories ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE faq_categories
SET is_active = COALESCE(is_active, TRUE),
    is_deleted = COALESCE(is_deleted, FALSE),
    created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
    updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP);

ALTER TABLE faq_categories ALTER COLUMN is_active SET DEFAULT TRUE;
ALTER TABLE faq_categories ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE faq_categories ALTER COLUMN is_deleted SET DEFAULT FALSE;
ALTER TABLE faq_categories ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE faq_categories ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE faq_categories ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE faq_categories ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE faq_categories ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE faqs ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE faqs
SET is_active = COALESCE(is_active, TRUE),
    is_deleted = COALESCE(is_deleted, FALSE),
    created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
    updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP);

ALTER TABLE faqs ALTER COLUMN is_active SET DEFAULT TRUE;
ALTER TABLE faqs ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE faqs ALTER COLUMN is_deleted SET DEFAULT FALSE;
ALTER TABLE faqs ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE faqs ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE faqs ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE faqs ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE faqs ALTER COLUMN updated_at SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_media_created_at ON media(created_at);
CREATE INDEX IF NOT EXISTS idx_pages_created_at ON pages(created_at);
CREATE INDEX IF NOT EXISTS idx_page_sections_page_order ON page_sections(page_id, display_order);
CREATE INDEX IF NOT EXISTS idx_home_sections_display_order ON home_sections(display_order);
CREATE INDEX IF NOT EXISTS idx_banners_created_at ON banners(created_at);
CREATE INDEX IF NOT EXISTS idx_testimonials_created_at ON testimonials(created_at);
CREATE INDEX IF NOT EXISTS idx_lookbooks_created_at ON lookbooks(created_at);
CREATE INDEX IF NOT EXISTS idx_faq_categories_display_order ON faq_categories(display_order);
CREATE INDEX IF NOT EXISTS idx_faqs_display_order ON faqs(display_order);
